repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.0 
    hooks:
      - id: ruff
        name: ruff
        language: python
        entry: ruff check . --fix
        types: [python]