site_name: ""
site_url: "https://github.com/"
site_description: ""
site_author: ""

# Repository settings for edit links
repo_url: "https://github.com/"
repo_name: ""
edit_uri: "blob/main/docs"

# Theme configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link
  favicon: "_static/imgs/favicon.ico"
  logo: "_static/imgs/pbat.svg"

# Navigation structure
nav:
  - Home: 
      - Overview: index.md
      - Installation: installation.md
      - Quickstart: quickstart.md
  - Development:
    - Changelog: changelog.md
    - Contributing: contributing.md
    - Code of Conduct: code_of_conduct.md
    - License: license.md



# Markdown extensions and plugins
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - mkdocs_graphviz
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2:
      version: 11.4.0
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
  - bibtex:
      bib_file: "docs/refs.bib"
  - include-markdown
  - git-revision-date-localized:
      locale: "en"
  - mkdocs-jupyter

# Paths to static files (CSS, JS, images)
extra_css:
  - "_static/stylesheets/custom.css"

extra_javascript:
  - "_static/javascripts/config.js"
  - "_static/javascripts/custom.js"
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

# Static files to include
extra:
  css:
    - "_static/stylesheets/custom.css"
  js:
    - "_static/javascripts/custom.js"

use_directory_urls: true
strict: false
